ci: make action to fail at pr code quality

diff --git a/.github/workflows/pr-test-pipeline.yml b/.github/workflows/pr-test-pipeline.yml
--- a/.github/workflows/pr-test-pipeline.yml
+++ b/.github/workflows/pr-test-pipeline.yml
@@ -21,12 +21,12 @@ jobs:
       - name: Cache Gradle dependencies
         uses: actions/cache@v4
         with:
-           path: |
-             ~/.gradle/caches
-             ~/.gradle/wrapper
-           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-           restore-keys: |
-             ${{ runner.os }}-gradle-
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
 
       - name: Run tests
         run: ./gradlew test
@@ -59,21 +59,29 @@ jobs:
 
       - name: Run Detekt
         id: detekt
-        run: ./gradlew detekt
+        continue-on-error: true
+        run: |
+          ./gradlew detekt
 
       - name: Check if Detekt report is empty
         id: check_detekt_report
         run: |
           if [ -s app/build/reports/detekt/detekt.md ]; then
-            echo "Detekt report is not empty"
-            exit 0
-          else
-            echo "Detekt report is empty"
-            exit 1
-          fi
+          echo "Detekt report is not empty"
+          exit 0
+            else
+          echo "Detekt report is empty"
+          exit 1
+            fi
 
       - name: Comment PR with Detekt report
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           path: app/build/reports/detekt/detekt.md
+
+      - name: Fail if Detekt failed
+        if: steps.detekt.outcome != 'success'
+        run: |
+          echo "Detekt encountered an error. Failing the workflow."
+          exit 1
